spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ine3
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: false
        format_sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
logging:
  level:
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
  file:
    name: ./logs/ine3app.log
    append: true
  rolling:
    policy: timeBased
    file-name-pattern: ./logs/ine3app-%d{yyyy-MM-dd}.%i.log
    max-history: 3
    max-file-size: 10MB
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, env
      base-path: /actuator
pocketBase:
  host: http://127.0.0.1:8090/
  collectionName: admin
  username: ine3pocketbase@gmail.com
  password: 1234567890